#!/usr/bin/env python3
"""Mirror the reviews written on other sites into the blog.

Every review on the accounts in ``data/reviews.toml`` becomes one post under
``content/blog/reviews/<site>/``, dated when the review was posted, so the
blog feed interleaves them with everything else in the order they were
written. The posts are generated and owned by this script: each run rewrites
every one of them from the source and deletes the ones whose review has gone.
The sources are the copy that matters -- fix an old review where it was
written, then pull it back down.

Three sources, three ways in:

``steam``
    The profile's ``/recommended/`` pages for the list of games, then each
    review's own page, which is the only place Steam prints the minute a
    review was posted and the hours played at the time. Requested with a UTC
    timezone cookie so the times it prints are UTC.
``goodreads``
    The shelf's RSS feed, which carries the review HTML, the rating and the
    dates. Goodreads hides review pages behind a sign-in, and the feed drops
    spoiler-tagged passages, leaving the words ``[spoilers removed]`` where
    one was; each becomes a link to the review where the passage still is.
``vndb``
    The user's review list and each review's page, then one call to the VNDB
    API for the novels' titles, covers and release dates.

Nothing here is automatic on purpose. ``pull`` rewrites the posts and leaves
the result in the working tree to be read as a diff and committed by hand;
``check`` does the same work without writing and reports how far behind the
committed posts are, which is all CI does with it.

Usage::

    python tools/reviews.py pull                  # every site
    python tools/reviews.py pull steam vndb       # just these
    python tools/reviews.py check                 # report drift, write nothing
    python tools/reviews.py check --github        # ...as CI annotations
"""

from __future__ import annotations

import argparse
import html
import json
import logging
import os
import re
import sys
import time
import tomllib
import unicodedata
import urllib.error
import urllib.parse
import urllib.request

# Only ever fed the Goodreads feed this script asked for.
import xml.etree.ElementTree as ET  # ruff: ignore[suspicious-xml-etree-import]
from dataclasses import dataclass, field
from datetime import UTC, datetime, timedelta
from email.utils import parsedate_to_datetime
from html.parser import HTMLParser
from pathlib import Path
from typing import TYPE_CHECKING, Any
from zoneinfo import ZoneInfo

if TYPE_CHECKING:
    from collections.abc import Callable, Iterable

_logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG = REPO_ROOT / "data" / "reviews.toml"
CONTENT = REPO_ROOT / "content" / "blog" / "reviews"

SITES = ("steam", "goodreads", "vndb")

# Identifies the script to the sites it reads. Steam answers an unknown agent
# with the same page it gives a browser, so there is no reason to pretend.
USER_AGENT = (
    "Mozilla/5.0 (compatible; wirenook-reviews/1.0;"
    " +https://github.com/CassidyPrather/cassidyprather.github.io)"
)

# A pause between requests to the same site. A full Steam pull is a request
# per review, and nothing about this is urgent.
POLITE_DELAY_S = 0.5

# The first line of every generated post. Also how the script knows a file
# under content/blog/reviews/ is its own to rewrite or delete.
GENERATED_MARK = "# Generated by tools/reviews.py"


@dataclass
class Review:
    """One review, as every source is boiled down to.

    ``fields`` holds what only one site has (Steam's thumb, Goodreads' stars,
    VNDB's vote) and is written under ``review:`` in front matter verbatim.
    """

    site: str
    key: str
    title: str
    date: datetime
    url: str
    item_url: str
    body: str
    updated: datetime | None = None
    image: str = ""
    image_width: int = 0
    image_height: int = 0
    fields: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------- fetching


def fetch(
    url: str, *, data: bytes | None = None, headers: dict[str, str] | None = None
) -> str:
    """GET (or POST, given ``data``) a URL and return the body as text.

    Retries with backoff, because a full pull is a couple of hundred requests
    and one dropped connection should not throw the rest away.

    :param url: Absolute http(s) URL.
    :param data: Request body; makes this a POST.
    :param headers: Extra request headers.
    :return: The decoded response body.
    :raises urllib.error.URLError: When every attempt fails.
    """
    if not url.startswith("https://"):
        msg = f"refusing to fetch non-https URL {url!r}"
        raise ValueError(msg)
    # The scheme is checked above, which is the whole of what this rule is for.
    request = urllib.request.Request(  # ruff: ignore[suspicious-url-open-usage]
        url,
        data=data,
        headers={"User-Agent": USER_AGENT, **(headers or {})},
    )
    delay = 2.0
    for attempt in range(5):
        try:
            with urllib.request.urlopen(request, timeout=30) as response:  # ruff: ignore[suspicious-url-open-usage]
                charset = response.headers.get_content_charset() or "utf-8"
                return response.read().decode(charset, errors="replace")
        except urllib.error.HTTPError as error:
            # A 4xx other than rate limiting will not get better by asking again.
            if error.code < 500 and error.code != 429:
                raise
            if attempt == 4:
                raise
        except (urllib.error.URLError, TimeoutError):
            if attempt == 4:
                raise
        _logger.debug("retrying %s in %.0fs", url, delay)
        time.sleep(delay)
        delay *= 2
    msg = "unreachable"
    raise AssertionError(msg)


# ---------------------------------------------------------- HTML cleanup

# Elements kept as themselves. Anything else is unwrapped -- its text stays,
# the tag goes -- except DROPPED, which goes with everything inside it.
KEPT = frozenset({
    "a", "b", "blockquote", "br", "code", "del", "div", "em", "hr", "i", "img",
    "li", "ol", "p", "pre", "s", "strong", "sub", "sup", "table", "tbody", "td",
    "th", "thead", "tr", "u", "ul",
})  # fmt: skip
DROPPED = frozenset({
    "button", "embed", "form", "iframe", "input", "noscript", "object",
    "script", "select", "style", "template", "textarea",
})  # fmt: skip
VOID = frozenset({"br", "hr", "img"})
# Closing one of these starts a new line in the output, for the diff's sake.
BLOCK = frozenset({
    "blockquote", "div", "h3", "h4", "h5", "h6", "li", "ol", "p", "pre",
    "table", "tbody", "thead", "tr", "ul",
})  # fmt: skip
RENAMED = {
    "strike": "s",
    "h1": "h3",
    "h2": "h4",
    "h3": "h5",
    "h4": "h6",
    "h5": "h6",
    "h6": "h6",
}
# Steam's BBCode renders headings, tables and quote bylines as classed divs.
STEAM_DIVS = {
    "bb_h1": "h3",
    "bb_h2": "h4",
    "bb_h3": "h5",
    "bb_table": "table",
    "bb_table_tr": "tr",
    "bb_table_th": "th",
    "bb_table_td": "td",
    "bb_quoteauthor": "p",
}
LINK_FILTERS = (
    "https://steamcommunity.com/linkfilter/",
    "https://www.goodreads.com/linkfilter",
)


class _Cleaner(HTMLParser):
    """Reduce a review's HTML to plain, attribute-free structure.

    What comes out is safe to drop into a Markdown file as a raw HTML block:
    no scripts or handlers, no site-specific classes except the one this
    site's skins style (spoilers), links made absolute, and whitespace
    collapsed so the only line breaks are the ones the markup asks for.
    """

    def __init__(self, base: str) -> None:
        super().__init__(convert_charrefs=True)
        self.base = base
        self.out: list[str] = []
        # (source tag, emitted tag or "" when unwrapped), innermost last.
        self.stack: list[tuple[str, str]] = []
        # Depth inside a dropped element, and which element that is.
        self.skip = 0
        self.skip_tag = ""
        self.pre = 0

    def _open(self, tag: str, attrs: dict[str, str | None]) -> str:
        classes = set((attrs.get("class") or "").split())
        if tag == "span" and classes & {"bb_spoiler", "spoiler"}:
            self.out.append('<span class="review-spoiler" tabindex="0">')
            return "span"
        if tag == "div":
            for name, mapped in STEAM_DIVS.items():
                if name in classes:
                    self.out.append(f"<{mapped}>")
                    return mapped
            if "quote" in classes:
                self.out.append("<blockquote>")
                return "blockquote"
        tag = RENAMED.get(tag, tag)
        if tag == "a":
            href = _absolute(self.base, attrs.get("href") or "")
            if not href:
                return ""
            self.out.append(f'<a href="{html.escape(href)}">')
            return "a"
        if tag == "img":
            src = _absolute(self.base, attrs.get("src") or "")
            if src:
                alt = html.escape(attrs.get("alt") or "")
                self.out.append(
                    f'<img src="{html.escape(src)}" alt="{alt}" loading="lazy">'
                )
            return ""
        if tag in KEPT or tag in RENAMED.values():
            self.out.append(f"<{tag}>")
            if tag == "br":
                self.out.append("\n")
            return tag
        return ""

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if self.skip:
            self.skip += tag == self.skip_tag
            return
        attributes = dict(attrs)
        # Steam follows every outbound link with the bare hostname in
        # brackets, its own warning about where the link goes. The href says
        # the same thing.
        host = tag == "span" and "bb_link_host" in (attributes.get("class") or "")
        if tag in DROPPED or host:
            if tag not in VOID:
                self.skip, self.skip_tag = 1, tag
            return
        emitted = self._open(tag, attributes)
        if tag in VOID:
            return
        if emitted == "pre":
            self.pre += 1
        self.stack.append((tag, emitted))

    def handle_startendtag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        self.handle_starttag(tag, attrs)
        if tag not in VOID:
            self.handle_endtag(tag)

    def handle_endtag(self, tag: str) -> None:
        if self.skip:
            self.skip -= tag == self.skip_tag
            return
        for depth in range(len(self.stack) - 1, -1, -1):
            if self.stack[depth][0] == tag:
                while len(self.stack) > depth:
                    self._close(self.stack.pop()[1])
                return

    def _close(self, emitted: str) -> None:
        if not emitted:
            return
        if emitted == "pre":
            self.pre -= 1
        self.out.append(f"</{emitted}>")
        if emitted in BLOCK:
            self.out.append("\n")

    def handle_data(self, data: str) -> None:
        if self.skip:
            return
        if not self.pre:
            data = re.sub(r"\s+", " ", data)
        self.out.append(html.escape(data, quote=False))

    def result(self) -> str:
        while self.stack:
            self._close(self.stack.pop()[1])
        return "".join(self.out)


def _absolute(base: str, href: str) -> str:
    """Resolve a link against its page and strip the sites' redirect wrappers.

    :param base: URL of the page the link appeared on.
    :param href: The link as written.
    :return: An absolute http(s) URL, or "" for anything else.
    """
    href = urllib.parse.urljoin(base, html.unescape(href.strip()))
    if href.startswith(LINK_FILTERS):
        query = urllib.parse.parse_qs(urllib.parse.urlsplit(href).query)
        href = (query.get("u") or query.get("url") or [""])[0]
    return href if urllib.parse.urlsplit(href).scheme in {"http", "https"} else ""


def clean_html(markup: str, base: str) -> str:
    """Normalise a review body into a diffable, Markdown-safe HTML fragment.

    No line of the result is blank: a blank line would end the raw HTML block
    Goodmark is passing through untouched, and the rest of the review would be
    read as Markdown -- where a Goodreads review's literal ``*asterisks*``
    would turn into emphasis the original never had.

    :param markup: The review HTML as the site serves it.
    :param base: URL of the page it came from, for resolving links.
    :return: The cleaned fragment.
    """
    cleaner = _Cleaner(base)
    cleaner.feed(markup)
    cleaner.close()
    lines = (line.strip() for line in cleaner.result().split("\n"))
    text = "\n".join(line for line in lines if line)
    # Leading and trailing breaks are layout the sites add, not the review's.
    text = re.sub(r"^(?:<br>\s*)+|(?:\s*<br>)+$", "", text)
    # Hugo would read these as the start of a shortcode, even in raw HTML.
    return text.replace("{{", "&#123;&#123;").replace("}}", "&#125;&#125;")


def _inner(markup: str, opening: str, tag: str) -> str:
    """Return what sits inside the first element that starts with ``opening``.

    Counts nesting, which the regexes elsewhere here cannot.

    :param markup: The page.
    :param opening: The element's opening tag, or enough of it to be unique.
    :param tag: The element's tag name.
    :return: Its inner HTML, or "" when it is not on the page.
    """
    start = markup.find(opening)
    if start < 0:
        return ""
    # From the end of ``opening``, so one that spans several tags still lands
    # inside the last of them.
    start = markup.index(">", start + len(opening) - 1) + 1
    depth = 1
    for match in re.compile(rf"<(/?){tag}\b[^>]*>", re.IGNORECASE).finditer(
        markup, start
    ):
        depth += -1 if match.group(1) else 1
        if depth == 0:
            return markup[start : match.start()]
    return markup[start:]


def _text(markup: str) -> str:
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", markup))).strip()


# ------------------------------------------------------------------ Steam

STEAM = "https://steamcommunity.com"
STEAM_HEADERS = {
    # Steam prints every time in the reader's zone, taken from this cookie.
    # UTC means the times it prints need no guessing about.
    "Cookie": "timezoneOffset=0,0; Steam_Language=english",
    "Accept-Language": "en-US,en;q=0.8",
}
STEAM_STAMP = re.compile(
    r"(Posted|Updated):\s*([A-Z][a-z]{2})\w* (\d{1,2})(?:, (\d{4}))?"
    r" @ (\d{1,2}):(\d{2})([ap]m)",
)
MONTHS = {
    name: number
    for number, name in enumerate(
        (
            "Jan",
            "Feb",
            "Mar",
            "Apr",
            "May",
            "Jun",
            "Jul",
            "Aug",
            "Sep",
            "Oct",
            "Nov",
            "Dec",
        ),
        start=1,
    )
}


def _steam_stamp(match: re.Match[str], now: datetime) -> datetime:
    """Turn one of Steam's "Oct 19, 2018 @ 5:29am" stamps into a UTC time.

    Steam leaves the year off anything from the current one.

    :param match: A ``STEAM_STAMP`` match.
    :param now: The current time, to supply that year.
    :return: The timestamp, in UTC.
    """
    _, month, day, year, hour, minute, half = match.groups()
    hour_24 = int(hour) % 12 + (12 if half == "pm" else 0)
    stamp = datetime(
        int(year or now.year), MONTHS[month], int(day), hour_24, int(minute), tzinfo=UTC
    )
    # A year-less stamp from late December, read in early January.
    if not year and stamp > now + timedelta(days=1):
        stamp = stamp.replace(year=stamp.year - 1)
    return stamp


def pull_steam(account: dict[str, Any]) -> list[Review]:
    """Read every review on a Steam profile.

    :param account: The ``[steam]`` table from the config.
    :return: The reviews, in no particular order.
    """
    profile = f"{STEAM}/profiles/{account['id']}/recommended/"
    apps: list[str] = []
    for page in range(1, 1000):
        listing = fetch(f"{profile}?p={page}&l=english", headers=STEAM_HEADERS)
        found = [
            app
            for app in dict.fromkeys(re.findall(r"/recommended/(\d+)/", listing))
            if app not in apps
        ]
        if not found:
            break
        apps.extend(found)
        time.sleep(POLITE_DELAY_S)
    _logger.info("steam: %d review(s) listed", len(apps))

    now = datetime.now(UTC)
    reviews = []
    for app in apps:
        url = f"{profile}{app}/"
        page = fetch(f"{url}?l=english", headers=STEAM_HEADERS)
        time.sleep(POLITE_DELAY_S)
        title = re.search(
            r'<meta property="og:title" content="[^"]*?Review for ([^"]*)"', page
        )
        image = re.search(r'<meta property="og:image" content="([^"]+)"', page)
        verdict = _text(_inner(page, '<div class="ratingSummary"', "div"))
        hours = _text(_inner(page, '<div class="playTime"', "div"))
        stamps = {
            m.group(1): _steam_stamp(m, now)
            for m in STEAM_STAMP.finditer(
                _text(_inner(page, '<div class="recommendation_date"', "div"))
            )
        }
        if not title or "Posted" not in stamps or not verdict:
            msg = f"steam: could not read the review at {url}"
            raise ValueError(msg)
        at_review = re.search(r"\(([\d,.]+) hrs at review time\)", hours)
        on_record = re.search(r"([\d,.]+) hrs on record", hours)
        # The hours played when the review was written, which is the number
        # that belongs to the review and the only one that holds still: the
        # running total changes every time the game is opened. Steam prints
        # the at-review figure only once the two differ, so until then the
        # total *is* it.
        played = at_review or on_record
        header = page[: page.find('id="ReviewText"')]
        reviews.append(
            Review(
                site="steam",
                key=app,
                title=html.unescape(title.group(1)).strip(),
                date=stamps["Posted"],
                updated=stamps.get("Updated"),
                url=url,
                item_url=f"https://store.steampowered.com/app/{app}/",
                body=clean_html(_inner(page, '<div id="ReviewText"', "div"), url),
                # The ?t= cache-buster changes whenever the art does, which
                # would rewrite the post for a change to Steam's CDN.
                image=html.unescape(image.group(1)).split("?")[0] if image else "",
                image_width=460 if image else 0,
                image_height=215 if image else 0,
                fields={
                    "recommended": verdict.casefold() == "recommended",
                    "hours": float(played.group(1).replace(",", ""))
                    if played
                    else None,
                    "early_access": "early_access_review" in header,
                    "free": 'class="received_compensation"' in header,
                },
            ),
        )
    return reviews


# -------------------------------------------------------------- Goodreads

GOODREADS = "https://www.goodreads.com"
# Goodreads' own words for each star count, which its review pages print in
# place of the number.
GOODREADS_RATINGS = {
    1: "did not like it",
    2: "it was ok",
    3: "liked it",
    4: "really liked it",
    5: "it was amazing",
}


def pull_goodreads(account: dict[str, Any]) -> list[Review]:
    """Read every review on a Goodreads account.

    :param account: The ``[goodreads]`` table from the config.
    :return: The reviews, in no particular order.
    """
    items: list[ET.Element] = []
    for page in range(1, 1000):
        feed = fetch(
            f"{GOODREADS}/review/list_rss/{account['id']}?shelf=%23ALL%23&page={page}"
        )
        found = ET.fromstring(feed).findall("./channel/item")  # ruff: ignore[suspicious-xml-element-tree-usage]
        if not found:
            break
        items.extend(found)
        time.sleep(POLITE_DELAY_S)

    reviews = []
    for item in items:
        body = (item.findtext("user_review") or "").strip()
        if not body:
            # Shelved, maybe rated, never reviewed. Nothing to post.
            continue
        guid = item.findtext("guid") or ""
        key = re.search(r"/review/show/(\d+)", guid)
        if not key:
            msg = f"goodreads: no review id in {guid!r}"
            raise ValueError(msg)
        url = f"{GOODREADS}/review/show/{key.group(1)}"
        book = item.findtext("book_id") or ""
        rating = int(item.findtext("user_rating") or 0)
        read_at = (item.findtext("user_read_at") or "").strip()
        published = (item.findtext("book_published") or "").strip()
        link = html.escape(url)
        spoiler = f'<a class="review-spoiler-link" href="{link}">(view spoiler)</a>'
        body = clean_html(body, url).replace("[spoilers removed]", spoiler)
        reviews.append(
            Review(
                site="goodreads",
                key=key.group(1),
                title=(item.findtext("title") or "").strip(),
                # When the book went onto the "read" shelf, which is when a
                # review gets written. The feed has no date for the review
                # itself, and user_date_created is when the book was first
                # shelved at all -- often to-read, months or years earlier.
                date=parsedate_to_datetime(item.findtext("user_date_added") or ""),
                url=url,
                item_url=f"{GOODREADS}/book/show/{book}",
                body=body,
                image=(item.findtext("book_large_image_url") or "").strip(),
                fields={
                    "rating": rating,
                    "rating_text": GOODREADS_RATINGS.get(rating, ""),
                    "author": (item.findtext("author_name") or "").strip(),
                    "published": int(published) if published.isdigit() else None,
                    "read": parsedate_to_datetime(read_at).date().isoformat()
                    if read_at
                    else None,
                },
            ),
        )
    return reviews


# ------------------------------------------------------------------- VNDB

VNDB = "https://vndb.org"
VNDB_API = "https://api.vndb.org/kana"
# VNDB rates every cover image on two 0-2 scales by user vote. Under 0.5 on
# both is what it calls "safe" and shows by default, and nothing past that is
# going on a page this site serves.
VNDB_SAFE = 0.5


def pull_vndb(account: dict[str, Any]) -> list[Review]:
    """Read every review on a VNDB account.

    :param account: The ``[vndb]`` table from the config.
    :return: The reviews, in no particular order.
    """
    ids: list[str] = []
    for page in range(1, 1000):
        listing = fetch(f"{VNDB}/w?u={account['id']}&p={page}")
        found = [
            w
            for w in dict.fromkeys(re.findall(r'href="/(w\d+)"', listing))
            if w not in ids
        ]
        if not found:
            break
        ids.extend(found)
        time.sleep(POLITE_DELAY_S)

    pages: dict[str, str] = {}
    for w in ids:
        pages[w] = fetch(f"{VNDB}/{w}")
        time.sleep(POLITE_DELAY_S)

    subjects: dict[str, str] = {}
    for w, page in pages.items():
        subject = re.search(r'<td>Subject</td><td><a href="/(v\d+)"', page)
        if not subject:
            msg = f"vndb: no subject on {VNDB}/{w}"
            raise ValueError(msg)
        subjects[w] = subject.group(1)
    novels = _vndb_novels(sorted(set(subjects.values())))

    reviews = []
    for w, page in pages.items():
        url = f"{VNDB}/{w}"
        vn = subjects[w]
        novel = novels.get(vn, {})
        posted = re.search(r'<a href="/u\d+">[^<]*</a> on (\d{4}-\d{2}-\d{2})', page)
        updated = re.search(r"[Ll]ast updated on (\d{4}-\d{2}-\d{2})", page)
        vote = re.search(r"Vote: ([\d.]+)", page)
        if not posted:
            msg = f"vndb: could not read the review at {url}"
            raise ValueError(msg)
        image = novel.get("image") or {}
        safe = (
            image.get("url")
            and image.get("sexual", 2) < VNDB_SAFE
            and image.get("violence", 2) < VNDB_SAFE
        )
        width, height = image.get("dims") or (0, 0)
        developers = [d["name"] for d in novel.get("developers") or []]
        reviews.append(
            Review(
                site="vndb",
                key=w,
                title=novel.get("title")
                or _text(_inner(page, "<h1>", "h1")).removeprefix("Review of "),
                date=datetime.fromisoformat(posted.group(1)),
                updated=datetime.fromisoformat(updated.group(1)) if updated else None,
                url=url,
                item_url=f"{VNDB}/{vn}",
                body=clean_html(_inner(page, "<td>Review</td><td", "td"), url),
                image=image["url"] if safe else "",
                image_width=width if safe else 0,
                image_height=height if safe else 0,
                fields={
                    # Out of ten, the way VNDB prints it.
                    "vote": float(vote.group(1)) if vote else None,
                    "original_title": novel.get("alttitle") or "",
                    # A language tag, for the original title's lang attribute.
                    "original_language": novel.get("olang") or "",
                    "released": novel.get("released") or "",
                    "developers": developers,
                    "spoilers": "This review contains spoilers" in page,
                },
            ),
        )
    return reviews


def _vndb_novels(ids: list[str]) -> dict[str, dict[str, Any]]:
    """Look up the reviewed novels in one API call.

    :param ids: VNDB ids, ``v`` and all.
    :return: The API's record for each, by id.
    """
    if not ids:
        return {}
    filters: list[Any] = [["id", "=", vn] for vn in ids]
    query = {
        "filters": filters[0] if len(filters) == 1 else ["or", *filters],
        "fields": (
            "title, alttitle, olang, released, developers.name,"
            " image.url, image.dims, image.sexual, image.violence"
        ),
        "results": 100,
    }
    response = fetch(
        f"{VNDB_API}/vn",
        data=json.dumps(query).encode(),
        headers={"Content-Type": "application/json"},
    )
    return {novel["id"]: novel for novel in json.loads(response)["results"]}


PULLERS: dict[str, Callable[[dict[str, Any]], list[Review]]] = {
    "steam": pull_steam,
    "goodreads": pull_goodreads,
    "vndb": pull_vndb,
}


# -------------------------------------------------------------- rendering


def slugify(text: str) -> str:
    ascii_text = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode()
    slug = re.sub(r"[^a-z0-9]+", "-", ascii_text.lower().replace("'", "")).strip("-")
    return slug[:60].rstrip("-")


def _yaml(value: object) -> str:
    """Write a scalar or list as YAML.

    JSON is YAML, so everything but dates goes through ``json.dumps`` and
    comes out quoted and escaped correctly without a YAML library.

    :param value: What to write.
    :return: Its YAML spelling.
    """
    if isinstance(value, datetime):
        return value.isoformat()
    return json.dumps(value, ensure_ascii=False)


def render(review: Review, slug: str, zone: ZoneInfo, account: dict[str, Any]) -> str:
    """Write one review out as a blog post.

    :param review: The review.
    :param slug: Its URL slug, already made unique within the site.
    :param zone: The zone timestamps are written in.
    :param account: The site's table from the config.
    :return: The whole file.
    """

    def local(stamp: datetime) -> datetime:
        # VNDB gives a bare date; it is a date where the reviewer was.
        if stamp.tzinfo is None:
            return stamp.replace(tzinfo=zone)
        return stamp.astimezone(zone)

    meta: list[tuple[str, object]] = [
        ("site", review.site),
        ("url", review.url),
    ]
    if review.updated and review.updated != review.date:
        meta.append(("updated", local(review.updated)))
    meta.append(("item_url", review.item_url))
    if review.image:
        meta.append(("image", review.image))
    if review.image_width and review.image_height:
        meta += [
            ("image_width", review.image_width),
            ("image_height", review.image_height),
        ]
    meta += list(review.fields.items())
    lines = [
        "---",
        f"{GENERATED_MARK} from {account['name']}. Edit the review at",
        f"# {review.url} and pull it again; changes made here are overwritten.",
        f"title: {_yaml(review.title)}",
        f"date: {local(review.date).isoformat()}",
        f"slug: {_yaml(slug)}",
        'type: "review"',
        f"theme: {_yaml(review.site)}",
        'tags: ["review"]',
        "review:",
        # An absent field is left out rather than written empty, so a review
        # that gains one later shows up in the diff as a line added.
        *(
            f"  {key}: {_yaml(value)}"
            for key, value in meta
            if value is not None and value not in ("", [])
        ),
        "---",
        "",
        '<div class="review-text">',
        review.body,
        "</div>",
        "",
    ]
    return "\n".join(lines)


def plan(
    site: str, reviews: Iterable[Review], zone: ZoneInfo, account: dict[str, Any]
) -> dict[Path, str]:
    """Work out every file a site's reviews should produce.

    The file is named for the review's id at the source, which never changes
    and is what the Atom feed keys an entry on (layouts/blog/list.rss.xml), so
    a retitled game is an edited entry rather than a new one. The URL is
    named for the title, through ``slug``.

    :param site: Which site.
    :param reviews: Its reviews.
    :param zone: The zone timestamps are written in.
    :param account: The site's table from the config.
    :return: Path to contents.
    """
    files: dict[Path, str] = {}
    taken: set[str] = set()
    for review in sorted(reviews, key=lambda r: (r.date.replace(tzinfo=None), r.key)):
        slug = slugify(review.title) or review.key
        if slug in taken:
            slug = f"{slug}-{slugify(review.key)}"
        taken.add(slug)
        path = CONTENT / site / f"{site}-{slugify(review.key)}.md"
        files[path] = render(review, slug, zone, account)
    return files


def owned(site: str) -> set[Path]:
    """Return the files already on disk that this script generated for a site.

    :param site: Which site.
    :return: Their paths.
    """
    directory = CONTENT / site
    if not directory.is_dir():
        return set()
    return {
        path
        for path in directory.glob("*.md")
        if GENERATED_MARK
        in "".join(path.read_text(encoding="utf-8").split("\n", 2)[1:2])
    }


@dataclass
class Drift:
    added: list[Path] = field(default_factory=list)
    changed: list[Path] = field(default_factory=list)
    removed: list[Path] = field(default_factory=list)

    def __len__(self) -> int:
        return len(self.added) + len(self.changed) + len(self.removed)


def compare(site: str, files: dict[Path, str]) -> Drift:
    drift = Drift()
    for path, text in files.items():
        if not path.exists():
            drift.added.append(path)
        elif path.read_text(encoding="utf-8") != text:
            drift.changed.append(path)
    drift.removed = sorted(owned(site) - files.keys())
    return drift


# -------------------------------------------------------------------- CLI


def _load_config() -> tuple[dict[str, Any], ZoneInfo]:
    with CONFIG.open("rb") as handle:
        config = tomllib.load(handle)
    return config, ZoneInfo(config["timezone"])


def _gather(sites: list[str]) -> dict[str, tuple[dict[Path, str], Drift]]:
    config, zone = _load_config()
    results = {}
    for site in sites:
        _logger.info("%s: fetching", site)
        reviews = PULLERS[site](config[site])
        files = plan(site, reviews, zone, config[site])
        results[site] = (files, compare(site, files))
        _logger.info("%s: %d review(s)", site, len(files))
    return results


def _rel(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


def cmd_pull(sites: list[str]) -> int:
    """Rewrite the posts from the sources.

    A site is written only once all of it has been read, so a request that
    fails halfway leaves that site's posts as they were rather than half
    deleted.

    :param sites: Which sites to pull.
    :return: Process exit code.
    """
    for site, (files, drift) in _gather(sites).items():
        for path in drift.added + drift.changed:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(files[path], encoding="utf-8", newline="\n")
        for path in drift.removed:
            path.unlink()
        _logger.info(
            "%s: %d added, %d changed, %d removed",
            site,
            len(drift.added),
            len(drift.changed),
            len(drift.removed),
        )
        for label, paths in (
            ("+", drift.added),
            ("~", drift.changed),
            ("-", drift.removed),
        ):
            for path in paths:
                _logger.info("  %s %s", label, _rel(path))
    return 0


def cmd_check(sites: list[str], *, github: bool, strict: bool) -> int:
    """Report how far the committed posts are behind the sources.

    :param sites: Which sites to check.
    :param github: Also write workflow annotations and a job summary.
    :param strict: Exit 1 when anything is behind.
    :return: Process exit code.
    """
    results = _gather(sites)
    rows = []
    behind = 0
    for site, (files, drift) in results.items():
        behind += len(drift)
        rows.append((site, len(files), drift))
        _logger.info(
            "%s: %d new, %d changed, %d gone",
            site,
            len(drift.added),
            len(drift.changed),
            len(drift.removed),
        )
        for label, paths in (
            ("new", drift.added),
            ("changed", drift.changed),
            ("gone", drift.removed),
        ):
            for path in paths:
                _logger.info("  %s %s", label, _rel(path))
    verdict = (
        f"{behind} review post(s) behind;"
        " run `python tools/reviews.py pull` and commit the result"
        if behind
        else "every review post is up to date"
    )
    _logger.info("%s", verdict)
    if github:
        if behind:
            sys.stdout.write(f"::warning title=Reviews behind::{verdict}\n")
        summary = os.environ.get("GITHUB_STEP_SUMMARY")
        if summary:
            table = [
                "## Reviews",
                "",
                "| Site | At source | New | Changed | Gone |",
                "| --- | ---: | ---: | ---: | ---: |",
                *(
                    f"| {site} | {total} | {len(d.added)} | {len(d.changed)}"
                    f" | {len(d.removed)} |"
                    for site, total, d in rows
                ),
                "",
                verdict,
                "",
            ]
            with Path(summary).open("a", encoding="utf-8") as handle:
                handle.write("\n".join(table))
    return 1 if strict and behind else 0


def main() -> int:
    """Execute the CLI entry point.

    :return: Exit code (0 for success, non-zero for error).
    """
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "-v",
        "--verbose",
        action="count",
        default=0,
        help="Increase verbosity (can be repeated)",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)
    pull = subparsers.add_parser(
        "pull", help="Rewrite content/blog/reviews/ from the sources"
    )
    check = subparsers.add_parser(
        "check", help="Report what a pull would change; write nothing"
    )
    for sub in (pull, check):
        sub.add_argument(
            "sites",
            nargs="*",
            metavar="site",
            help=f"Sites to read (default: all of {', '.join(SITES)})",
        )
    check.add_argument(
        "--github",
        action="store_true",
        help="Emit a workflow annotation and a job summary",
    )
    check.add_argument(
        "--strict",
        action="store_true",
        help="Exit 1 when any post is behind its source",
    )
    args = parser.parse_args()
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(message)s",
    )
    unknown = sorted(set(args.sites) - set(SITES))
    if unknown:
        parser.error(
            f"unknown site(s): {', '.join(unknown)} (choose from {', '.join(SITES)})"
        )
    sites = list(dict.fromkeys(args.sites)) or list(SITES)
    try:
        if args.command == "pull":
            return cmd_pull(sites)
        return cmd_check(sites, github=args.github, strict=args.strict)
    except (urllib.error.URLError, ValueError, ET.ParseError) as error:
        _logger.error("%s", error)
        return 2


if __name__ == "__main__":
    sys.exit(main())
